### ISSUE TITLE
Page title variable uses block margin in develop

### ISSUE THREAD

**Issue by zenduo** [adaptlearning/adapt-contrib-vanilla#104]
Hey @kirsty-hames 

Just checking out the new theme updates, looking really good.

Had a question regarding the page-title.

It uses the block variable value to set the margin bottom. Should this be the case? All of the others have their own values.

.page-title {
        margin-bottom: @block-body-margin-bottom;
}

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#882
