### ISSUE TITLE
Should selection.json travel alongside fonts?

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-contrib-vanilla#159]
*selection.json* is a file that was produced by icomoon to make it easy to reselect icons. It was used to create the vanilla font files found in the *fonts* directory. It currently lives at vanilla root. Would it make more sense to store it in *fonts* with the files it created?

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#883
