### ISSUE TITLE
Is standardized padding in the most logical file?

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-contrib-vanilla#326]
While working with Vanilla v6.1.0, I had to track down component padding. I encountered the new standardized padding (#321). I have no issue with the change. But I was confused by where I found the code. Note that I was searching for the padding while in my local environment. I found it in _columns.less_. That made me scratch my head. I wasn't using columns. And it made me wonder if there was a collision/side-effect coming from the implementation of columns. I was about to report the issue when I discovered the existing issues regarding standardized padding and educated myself.

If I understand the rationale behind the standardized padding, it seems that a more logical place for this Less code would be in Vanilla/less/**core**/component.less. Placing it in [Vanilla/less/**project**/columns.less](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/project/columns.less) gives the impression that the padding styles would be invoked only when columns are used.

**Comment by guywillis** [comment]
You're absolutely right, Chuck. An oversight on my part with the development of columns and the conversion of padding.

Would you mind creating a PR to resolve the above please?
