### ISSUE TITLE
Small theme file shake up

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt-contrib-vanilla#331]
A couple of suggestions to make the theme structure a little more manageable.

* Split up the `theme-extras.less` file into smaller, more manageable and digestible, files. Potentially naming them `extas-block.less` `extras-component.less` etc. Open to suggestions on naming.
* Move `blend.less` and `filter.less` files from `project` folder into `_defaults`

**Comment by oliverfoster** [comment]
@guywillis is this done?
