### ISSUE TITLE
Body background color is not set

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-vanilla#349]
### Subject of the issue/enhancement/features
The body background color is currently not being set by the theme.  This can lead to the page background being inconsistent depending on the user's browser settings.

### Your environment
* Framework 5.x
* Browser: Firefox 103.0.2

### Steps to reproduce
Open up Firefox's browser settings and change the default background color to something other than white.

Firefox: Preferences > Manage Colors > Text and Background > Background

### Expected behaviour
Page background should be explicitly set by the theme.

### Actual behaviour
Page background falls back to using the browser background color setting

### Screenshots (if you can)
![no-body-bg-color](https://user-images.githubusercontent.com/898168/185184926-22665f2d-7c92-4c75-8fec-ad9f4e3d7cdf.jpg)

![Firefox-settings](https://user-images.githubusercontent.com/898168/185184719-8f9d14f5-6881-4f7b-a213-06ac6dd2c9e7.jpg)

### Recommendation
Set the background color on the body element with a new color variable (defaults to white).

**Comment by guywillis** [comment]
I can see arguments for both camps - ability to style the background of a course with a change of a variable vs retaining end user preferences.

Having tested the feature out in Firefox, even with a background colour defined on the `body` element the end user has the ability to override the values defined by the site paving the way for this feature to be added.

As this request relates to styling it should exist in the theme. Perhaps a colour defined in `_colors.less` and assigned in `global.less`
