### ISSUE TITLE
Vanilla Wiki - Updates

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt-contrib-vanilla#382]
## Subject of the issue
The [Vanilla wiki](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki) requires further edits and reviews to provide more clarification on the Vanilla theme. Using comments raised in this [issue](https://github.com/adaptlearning/adapt-contrib-vanilla/issues/345) to produce an initial list of tasks.

### Custom classes

- [x] Clarify whether classes applied to contentObjects are directed at the menu item or the page
- [x] Clarify comp-header-bg-color custom class effects

### Structure

- [x] Write up description regarding other files listed in project folder
- [x] Expand on template section to add further clarification
- [x] Provide a write up on schema files

#### Inline icons

- [x] Would it be possible to have an image next to the `Lorem ipsum dolor sit amet <span class='icon icon-arrow-down-2 inline-icon' aria-hidden='true'></span> consectetur adipiscing elit.` example to see the output?
- [x] Can the color of the icon be modified via an inline class?
- Note: at present, the color of the icon inherits from the color of the text it sits alongside. For the global body font color see [here](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/_defaults/_colors.less#L25). 
- [x] The image does not seem to fit as it's about 'Presentation Components'.

#### Icon breakdown

- [x] In the example code `icon-arrow-down-2` is mentioned but in the icon list `arrow-down-2` is provided as the icon name without the `icon-` prefix. Maybe it would be better to add the `icon-` prefix to all names in the list because then users can directly copy the names.
- Rather confusingly, the icon name refers to the source name for that particular icon. The custom icon font created through IcoMoon then prefixes that icon name with `.icon-` for use within Adapt. Agreed that it could be tightened up which I have done by adding a small section in before the tables.
- [x] Why is the Content ID relevant and how is it used?
- Currently, icons are bundled in Adapt as a custom font and each of these icons have an associated content id within that font. For the most part, you'll not need to use to the content id but it can useful as a be reference point when creating custom styles or when adding more icons to the font set.
- [x] Currently the list is sorted by Content ID but it would be better to sort it by icon groups meaning having all types of arrows in one group together for example.
- I agree here but it may be best to coincide this update until after we have implemented icons as inline svgs.
- [x] It's fine to have the image of the icons on top of each section but even better would be to have the individual icon images next to the icon names.
- I agree here but it may be best to coincide this update until after we have implemented icons as inline svgs.
- [x] I'd suggest not to have two blocks of icons (each with the columns icon, CSS class name and content ID) in one table but rather have two separate tables. This would improve readability.

 #### Framework Wiki

- [x] Update '[Styling your course](https://github.com/adaptlearning/adapt_framework/wiki/Styling-your-course)' Framework wiki page - new issue for this point raised within the [Framework repo](https://github.com/adaptlearning/adapt_framework/issues/3494)

**Comment by guywillis** [comment]
> * I'd suggest not to have two blocks of icons (each with the columns icon, CSS class name and content ID) in one table but rather have two separate tables. This would improve readability.

Unfortunately we're a little limited with what we can do with the displays of tables in the Markdown language. Though I have updated the tables to, hopefully, be easier to read. 

### Original
<img width="912" alt="Screenshot 2023-01-10 at 10 23 17" src="https://user-images.githubusercontent.com/11569678/211531580-877000c5-c74d-4c4e-b7b6-cfc80c03ca6a.png">

### Updated 
![Screenshot 2023-01-10 at 10 23 28](https://user-images.githubusercontent.com/11569678/211531604-2809a7d9-735b-499c-aa13-f771de4c77b8.png)

**Comment by jroed** [comment]
> Unfortunately we're a little limited with what we can do with the displays of tables in the Markdown language. Though I have updated the tables to, hopefully, be easier to read.

It's definitely an improvement. Thanks!

**Comment by guywillis** [comment]
Updates made to Vanilla wiki, closing issue.
