### ISSUE TITLE
Extra breakpoints required. Missing xlarge. 

### ISSUE THREAD

**Issue by StuartNicholls** [adaptlearning/adapt-contrib-vanilla#431]
Following the breakpoint update in core, we need to add in an extra large node for headers and backgrounds.

https://github.com/adaptlearning/adapt-contrib-vanilla/blob/aac3a2bdade9398bc9cf353dd40b64f5235096dd/js/themePageView.js#L46-L55

linked to issue #430 

We could add this issue in now and retain the existing functionality. See issue #430 as functionality may get updated at a later date in this issue.

**Comment by oliverfoster** [comment]
That code can mimic the boxMenu code, which is much simpler, less hard-codey and does the same thing:

https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/040166743e2a765a7d08bd5b4e6b08a7705ecf64/js/BoxMenuView.js#L73

**Comment by StuartNicholls** [comment]
@oliverfoster yep, lovely
