### ISSUE TITLE
Notify button - incorrect hover colors

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-vanilla#482]
### Subject of the issue
The Notify button hover states are incorrect and do not use `@notify-btn-hover` or `@notify-btn-inverted-hover`.

### Your environment
* FW 5.33.10
* Vanilla theme 9.13.1

### Steps to reproduce
1. Enable the language picker using the JSON from the [example.json](https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/master/example.json)
2. Override the notify button colors in your theme (see below)
3. Select an initial language
4. Click the language icon in the navbar to change the language
5. Hover over the buttons in the popup

Color variables to use:
```
@notify-btn: white;
@notify-btn-inverted: magenta;
@notify-btn-hover: magenta;
@notify-btn-inverted-hover: red;
```

### Expected behaviour
Button hover states should use the colors defined by `@notify-btn-hover` or `@notify-btn-inverted-hover`

### Actual behaviour
Hover colors are being overridden by [this style](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/cb5fc98607b042487566bab99daf4c784f5f2afd/less/core/button.less#L26) in _less/core/buttons.less_. That selector is more specific than the [selector](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/cb5fc98607b042487566bab99daf4c784f5f2afd/less/core/notify.less#L67) in _less/core/notify.less_. So, it ends up using `@btn-color-hover` and `@btn-color-inverted-hover` instead.

**Comment by kirsty-hames** [comment]
Good spot @swashbuck and this is one of many reasons why we need to review/update our approach on Adapt buttons (see existing issue https://github.com/adaptlearning/adapt-contrib-vanilla/issues/469).

Meanwhile, we could resolve the issue by applying the same `:not` logic to `.notify__btn` as per `.btn-text`.
