### ISSUE TITLE
@max-page-width variable is ignored for .page element

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-vanilla#493]
### Subject of the issue
The max-width of `.page` should be using the `@max-page-width` [value](https://github.com/adaptlearning/adapt-contrib-core/blob/0575f81b7cfb59f95fdb120e1b4aa58d3afd1397/less/core/page.less#L2). Instead, the Vanilla theme is [overriding](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/6d6946dee68141fe37e5072c7d6fde9b38965fb2/less/core/page.less#L3) this with a `max-width: inherit` style.

Is this intentional? If not, should we remove the `max-width: inherit` style?

<img width="157" alt="max-width-page" src="https://github.com/adaptlearning/adapt-contrib-vanilla/assets/898168/03e14643-2d71-4ae6-8fe9-2d82b423266e">

### Your environment
* Vanilla 9.14.1
* FW 5.35.0

### To reproduce
In your theme's CSS:
```
@body-background-color: #96D5E4;

.page {
  background-color: @white;
}
```

### Expected results
Blue body background color is visible on the sides.

<img src="https://github.com/adaptlearning/adapt-contrib-vanilla/assets/898168/4310c07e-d5fd-48f9-8a51-c60a4ae71948" width="500">

### Actual results
Entire page is white because `.page` is the full window width and does not use `@max-page-width`.

**Comment by swashbuck** [comment]
@guywillis Any thoughts on this?

**Comment by guywillis** [comment]
@swashbuck The preference at time of implementation was to plumb the container into core to match the rest of core Adapt but have the override in Vanilla so the visual impression is that Adapt goes to the edge of the screen but that it could be reverted with a small deletion of CSS.

**Comment by swashbuck** [comment]
@guywillis Would it make sense to remove the `max-width: inherit` style from the theme and set the default value of `@max-page-width` to 100%? That would be simpler to customize since only one variable would need to be changed rather than having to find the offending style.

**Comment by swashbuck** [comment]
Thanks, @guywillis . I've created PR #494 for this.

Question: do we still need the `@max-width` variable? From what I can tell, `@max-width` is only used to assign a value to `@max-page-width`. So, we could get by with only having `@max-page-width`. If we want to change it, I can create a separate ticket in Vanilla and the Core plugin.

**Comment by guywillis** [comment]
I believe it is in to support those updating from older versions of the theme.
