### ISSUE TITLE
Add background image settings to components

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-vanilla#511]
### Subject of the enhancement
Currently, you can add a background image to articles and blocks but not components. It would be useful to have this feature for components as well.

For components, I would suggest that we add `_backgroundImage` and `_backgroundStyles`:

```
"_vanilla": {
  "_backgroundImage": {
    "_xlarge": "",
    "_large": "",
    "_medium": "",
    "_small": ""
  },
  "_backgroundStyles": {
    "_backgroundSize": "",
    "_backgroundRepeat": "",
    "_backgroundPosition": ""
  }
}
```

### Screenshots
Here is an example from a project that we are working on. Notice the pattern behind the component text.
<img src="https://github.com/adaptlearning/adapt-contrib-vanilla/assets/898168/1ee2abe7-63af-4a3f-a1aa-9eff95ac1f3a" width="400">

**Comment by swashbuck** [comment]
@guywillis pointed out that this currently works in the FW. However, the necessary CSS for the background layer is missing. So, it won't work without this:

```
.component.has-bg-image > .background {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  background-repeat: no-repeat;
}
```

The CSS addition to [component.less](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/core/component.less) should be included in this PR.

**Comment by swashbuck** [comment]
For this PR, should we just add the missing CSS and skip the schema / AAT configurable options? What does everyone think?

**Comment by oliverfoster** [comment]
Seems fair. Make a note on Dan's issue that component backgrounds are needed and used also?
