### ISSUE TITLE
IE8 disabled state on buttons

### ISSUE THREAD

**Issue by zenduo** [adaptlearning/adapt-contrib-vanilla#70]
### Issue:
Using the ***develop branches***, viewing an MCQ (or any component with buttons) the ***feedback button which is disabled, doesn't render as the disabled styling should***.

### Detail:
***&:disabled*** is breaking this for IE8, replacing this with ***&[disabled="disabled"]*** fixes the issue. Is :disabled used for another browser?

https://github.com/adaptlearning/adapt-contrib-vanilla/blob/develop/less/buttons.less#L22

Tested in browserstack on IE8, Windows 7

**Comment by oliverfoster** [comment]
I believe :disabled is the new CSS selector for the disabled state. I suggest using both both selectors for the time being, it'll be easier to remove ie8 support when the time comes.

**Comment by zenduo** [comment]
Hey, i thought the same, however when I tried:

```&.disabled, &:disabled,  &[disabled="disabled"]{}``` it didn't work

```&.disabled, &[disabled="disabled"], &:disabled{}``` it didn't work

```&.disabled, &[disabled="disabled"]{}``` it worked....

The only way to make it work would be to duplicate the code and have a lonely:

```&[disabled="disabled"]{}``` for IE8 support

What are your thoughts, i'm happy to fork and send a merge request.

**Comment by oliverfoster** [comment]
the css3 :disabled attribute would be my preference for the majority of disabled styling with an ie8 section (separate if need be). I find it a bit odd that the styles don't play well together
I'm happy if you can produce a solution that works that is css3>forward looking.

**Comment by zenduo** [comment]
Fixed merged, closing
