### ISSUE TITLE
Margin causes article background to show through

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-vanilla#76]
https://github.com/adaptlearning/adapt-contrib-vanilla/blob/develop/less/component.less#L9

^needs to be changed to padding.

**Comment by oliverfoster** [comment]
this presents on iphone6 in portrait, when an article + block have no text and the first component - having a title - sits at the top of its block.

**Comment by kirsty-hames** [comment]
Component title no longer uses top margin. Issue resolved. https://github.com/adaptlearning/adapt-contrib-vanilla/blob/ABU-650/less/src/component.less
